<?php
/**
 * OAuthAppsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Integrations
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OAuthAppsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OAuthAppsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getApiV1OauthAppsGet
     *
     * Get OAuth App.
     *
     */
    public function testGetApiV1OauthAppsGet()
    {
    }

    /**
     * Test case for getApiV1OauthAppsList
     *
     * Get List of OAuth Apps.
     *
     */
    public function testGetApiV1OauthAppsList()
    {
    }

    /**
     * Test case for postApiV1OauthAppsCreate
     *
     * Create OAuth App.
     *
     */
    public function testPostApiV1OauthAppsCreate()
    {
    }

    /**
     * Test case for postApiV1OauthAppsDelete
     *
     * Delete OAuth App.
     *
     */
    public function testPostApiV1OauthAppsDelete()
    {
    }

    /**
     * Test case for postApiV1OauthAppsUpdate
     *
     * Update OAuth App.
     *
     */
    public function testPostApiV1OauthAppsUpdate()
    {
    }
}
