<?php
/**
 * Apiv1chatSendMessageMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Messaging
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * Apiv1chatSendMessageMessageTest Class Doc Comment
 *
 * @category    Class
 * @description Apiv1chatSendMessageMessage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Apiv1chatSendMessageMessageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Apiv1chatSendMessageMessage"
     */
    public function testApiv1chatSendMessageMessage()
    {
    }

    /**
     * Test attribute "t"
     */
    public function testPropertyT()
    {
    }

    /**
     * Test attribute "rid"
     */
    public function testPropertyRid()
    {
    }

    /**
     * Test attribute "msg"
     */
    public function testPropertyMsg()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "emoji"
     */
    public function testPropertyEmoji()
    {
    }

    /**
     * Test attribute "avatar"
     */
    public function testPropertyAvatar()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "tmid"
     */
    public function testPropertyTmid()
    {
    }

    /**
     * Test attribute "tshow"
     */
    public function testPropertyTshow()
    {
    }

    /**
     * Test attribute "blocks"
     */
    public function testPropertyBlocks()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }
}
