<?php
/**
 * SubscriptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Statistics
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getApiV1SubscriptionsGet
     *
     * Get All Subscriptions.
     *
     */
    public function testGetApiV1SubscriptionsGet()
    {
    }

    /**
     * Test case for getApiV1SubscriptionsGetOne
     *
     * Get Subscription Room.
     *
     */
    public function testGetApiV1SubscriptionsGetOne()
    {
    }

    /**
     * Test case for postApiV1SubscriptionsRead
     *
     * Mark Channel as Read.
     *
     */
    public function testPostApiV1SubscriptionsRead()
    {
    }

    /**
     * Test case for postApiV1SubscriptionsUnread
     *
     * Mark Channel as Unread.
     *
     */
    public function testPostApiV1SubscriptionsUnread()
    {
    }
}
