<?php
/**
 * InlineResponse20011User
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * User Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * InlineResponse20011User Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20011User implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_11_user';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        '_id' => 'string',
        'created_at' => 'string',
        'services' => '\Swagger\Client\Model\InlineResponse20011UserServices',
        'username' => 'string',
        'emails' => '\Swagger\Client\Model\InlineResponse20032Emails[]',
        'type' => 'string',
        'status' => 'string',
        'active' => 'bool',
        '_updated_at' => 'string',
        '__rooms' => 'string[]',
        'roles' => 'string[]',
        'name' => 'string',
        'settings' => '\Swagger\Client\Model\InlineResponse20011UserSettings',
        'last_login' => 'string',
        'status_connection' => 'string',
        'utc_offset' => 'int',
        'banners' => '\Swagger\Client\Model\InlineResponse20011UserBanners',
        'status_default' => 'string',
        'status_text' => 'string',
        'operator' => 'bool',
        'livechat_status_system_modified' => 'bool',
        'status_livechat' => 'string',
        'livechat_count' => 'int',
        'livechat' => '\Swagger\Client\Model\InlineResponse20011UserLivechat',
        'bio' => 'string',
        'nickname' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        '_id' => null,
        'created_at' => null,
        'services' => null,
        'username' => null,
        'emails' => null,
        'type' => null,
        'status' => null,
        'active' => null,
        '_updated_at' => null,
        '__rooms' => null,
        'roles' => null,
        'name' => null,
        'settings' => null,
        'last_login' => null,
        'status_connection' => null,
        'utc_offset' => null,
        'banners' => null,
        'status_default' => null,
        'status_text' => null,
        'operator' => null,
        'livechat_status_system_modified' => null,
        'status_livechat' => null,
        'livechat_count' => null,
        'livechat' => null,
        'bio' => null,
        'nickname' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_id' => '_id',
        'created_at' => 'createdAt',
        'services' => 'services',
        'username' => 'username',
        'emails' => 'emails',
        'type' => 'type',
        'status' => 'status',
        'active' => 'active',
        '_updated_at' => '_updatedAt',
        '__rooms' => '__rooms',
        'roles' => 'roles',
        'name' => 'name',
        'settings' => 'settings',
        'last_login' => 'lastLogin',
        'status_connection' => 'statusConnection',
        'utc_offset' => 'utcOffset',
        'banners' => 'banners',
        'status_default' => 'statusDefault',
        'status_text' => 'statusText',
        'operator' => 'operator',
        'livechat_status_system_modified' => 'livechatStatusSystemModified',
        'status_livechat' => 'statusLivechat',
        'livechat_count' => 'livechatCount',
        'livechat' => 'livechat',
        'bio' => 'bio',
        'nickname' => 'nickname'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_id' => 'setId',
        'created_at' => 'setCreatedAt',
        'services' => 'setServices',
        'username' => 'setUsername',
        'emails' => 'setEmails',
        'type' => 'setType',
        'status' => 'setStatus',
        'active' => 'setActive',
        '_updated_at' => 'setUpdatedAt',
        '__rooms' => 'setRooms',
        'roles' => 'setRoles',
        'name' => 'setName',
        'settings' => 'setSettings',
        'last_login' => 'setLastLogin',
        'status_connection' => 'setStatusConnection',
        'utc_offset' => 'setUtcOffset',
        'banners' => 'setBanners',
        'status_default' => 'setStatusDefault',
        'status_text' => 'setStatusText',
        'operator' => 'setOperator',
        'livechat_status_system_modified' => 'setLivechatStatusSystemModified',
        'status_livechat' => 'setStatusLivechat',
        'livechat_count' => 'setLivechatCount',
        'livechat' => 'setLivechat',
        'bio' => 'setBio',
        'nickname' => 'setNickname'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_id' => 'getId',
        'created_at' => 'getCreatedAt',
        'services' => 'getServices',
        'username' => 'getUsername',
        'emails' => 'getEmails',
        'type' => 'getType',
        'status' => 'getStatus',
        'active' => 'getActive',
        '_updated_at' => 'getUpdatedAt',
        '__rooms' => 'getRooms',
        'roles' => 'getRoles',
        'name' => 'getName',
        'settings' => 'getSettings',
        'last_login' => 'getLastLogin',
        'status_connection' => 'getStatusConnection',
        'utc_offset' => 'getUtcOffset',
        'banners' => 'getBanners',
        'status_default' => 'getStatusDefault',
        'status_text' => 'getStatusText',
        'operator' => 'getOperator',
        'livechat_status_system_modified' => 'getLivechatStatusSystemModified',
        'status_livechat' => 'getStatusLivechat',
        'livechat_count' => 'getLivechatCount',
        'livechat' => 'getLivechat',
        'bio' => 'getBio',
        'nickname' => 'getNickname'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_id'] = isset($data['_id']) ? $data['_id'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['services'] = isset($data['services']) ? $data['services'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
        $this->container['emails'] = isset($data['emails']) ? $data['emails'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['active'] = isset($data['active']) ? $data['active'] : null;
        $this->container['_updated_at'] = isset($data['_updated_at']) ? $data['_updated_at'] : null;
        $this->container['__rooms'] = isset($data['__rooms']) ? $data['__rooms'] : null;
        $this->container['roles'] = isset($data['roles']) ? $data['roles'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['settings'] = isset($data['settings']) ? $data['settings'] : null;
        $this->container['last_login'] = isset($data['last_login']) ? $data['last_login'] : null;
        $this->container['status_connection'] = isset($data['status_connection']) ? $data['status_connection'] : null;
        $this->container['utc_offset'] = isset($data['utc_offset']) ? $data['utc_offset'] : null;
        $this->container['banners'] = isset($data['banners']) ? $data['banners'] : null;
        $this->container['status_default'] = isset($data['status_default']) ? $data['status_default'] : null;
        $this->container['status_text'] = isset($data['status_text']) ? $data['status_text'] : null;
        $this->container['operator'] = isset($data['operator']) ? $data['operator'] : null;
        $this->container['livechat_status_system_modified'] = isset($data['livechat_status_system_modified']) ? $data['livechat_status_system_modified'] : null;
        $this->container['status_livechat'] = isset($data['status_livechat']) ? $data['status_livechat'] : null;
        $this->container['livechat_count'] = isset($data['livechat_count']) ? $data['livechat_count'] : null;
        $this->container['livechat'] = isset($data['livechat']) ? $data['livechat'] : null;
        $this->container['bio'] = isset($data['bio']) ? $data['bio'] : null;
        $this->container['nickname'] = isset($data['nickname']) ? $data['nickname'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['_id'];
    }

    /**
     * Sets _id
     *
     * @param string $_id _id
     *
     * @return $this
     */
    public function setId($_id)
    {
        $this->container['_id'] = $_id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets services
     *
     * @return \Swagger\Client\Model\InlineResponse20011UserServices
     */
    public function getServices()
    {
        return $this->container['services'];
    }

    /**
     * Sets services
     *
     * @param \Swagger\Client\Model\InlineResponse20011UserServices $services services
     *
     * @return $this
     */
    public function setServices($services)
    {
        $this->container['services'] = $services;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username username
     *
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets emails
     *
     * @return \Swagger\Client\Model\InlineResponse20032Emails[]
     */
    public function getEmails()
    {
        return $this->container['emails'];
    }

    /**
     * Sets emails
     *
     * @param \Swagger\Client\Model\InlineResponse20032Emails[] $emails emails
     *
     * @return $this
     */
    public function setEmails($emails)
    {
        $this->container['emails'] = $emails;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active active
     *
     * @return $this
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets _updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['_updated_at'];
    }

    /**
     * Sets _updated_at
     *
     * @param string $_updated_at _updated_at
     *
     * @return $this
     */
    public function setUpdatedAt($_updated_at)
    {
        $this->container['_updated_at'] = $_updated_at;

        return $this;
    }

    /**
     * Gets __rooms
     *
     * @return string[]
     */
    public function getRooms()
    {
        return $this->container['__rooms'];
    }

    /**
     * Sets __rooms
     *
     * @param string[] $__rooms __rooms
     *
     * @return $this
     */
    public function setRooms($__rooms)
    {
        $this->container['__rooms'] = $__rooms;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return string[]
     */
    public function getRoles()
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param string[] $roles roles
     *
     * @return $this
     */
    public function setRoles($roles)
    {
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \Swagger\Client\Model\InlineResponse20011UserSettings
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \Swagger\Client\Model\InlineResponse20011UserSettings $settings settings
     *
     * @return $this
     */
    public function setSettings($settings)
    {
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets last_login
     *
     * @return string
     */
    public function getLastLogin()
    {
        return $this->container['last_login'];
    }

    /**
     * Sets last_login
     *
     * @param string $last_login last_login
     *
     * @return $this
     */
    public function setLastLogin($last_login)
    {
        $this->container['last_login'] = $last_login;

        return $this;
    }

    /**
     * Gets status_connection
     *
     * @return string
     */
    public function getStatusConnection()
    {
        return $this->container['status_connection'];
    }

    /**
     * Sets status_connection
     *
     * @param string $status_connection status_connection
     *
     * @return $this
     */
    public function setStatusConnection($status_connection)
    {
        $this->container['status_connection'] = $status_connection;

        return $this;
    }

    /**
     * Gets utc_offset
     *
     * @return int
     */
    public function getUtcOffset()
    {
        return $this->container['utc_offset'];
    }

    /**
     * Sets utc_offset
     *
     * @param int $utc_offset utc_offset
     *
     * @return $this
     */
    public function setUtcOffset($utc_offset)
    {
        $this->container['utc_offset'] = $utc_offset;

        return $this;
    }

    /**
     * Gets banners
     *
     * @return \Swagger\Client\Model\InlineResponse20011UserBanners
     */
    public function getBanners()
    {
        return $this->container['banners'];
    }

    /**
     * Sets banners
     *
     * @param \Swagger\Client\Model\InlineResponse20011UserBanners $banners banners
     *
     * @return $this
     */
    public function setBanners($banners)
    {
        $this->container['banners'] = $banners;

        return $this;
    }

    /**
     * Gets status_default
     *
     * @return string
     */
    public function getStatusDefault()
    {
        return $this->container['status_default'];
    }

    /**
     * Sets status_default
     *
     * @param string $status_default status_default
     *
     * @return $this
     */
    public function setStatusDefault($status_default)
    {
        $this->container['status_default'] = $status_default;

        return $this;
    }

    /**
     * Gets status_text
     *
     * @return string
     */
    public function getStatusText()
    {
        return $this->container['status_text'];
    }

    /**
     * Sets status_text
     *
     * @param string $status_text status_text
     *
     * @return $this
     */
    public function setStatusText($status_text)
    {
        $this->container['status_text'] = $status_text;

        return $this;
    }

    /**
     * Gets operator
     *
     * @return bool
     */
    public function getOperator()
    {
        return $this->container['operator'];
    }

    /**
     * Sets operator
     *
     * @param bool $operator operator
     *
     * @return $this
     */
    public function setOperator($operator)
    {
        $this->container['operator'] = $operator;

        return $this;
    }

    /**
     * Gets livechat_status_system_modified
     *
     * @return bool
     */
    public function getLivechatStatusSystemModified()
    {
        return $this->container['livechat_status_system_modified'];
    }

    /**
     * Sets livechat_status_system_modified
     *
     * @param bool $livechat_status_system_modified livechat_status_system_modified
     *
     * @return $this
     */
    public function setLivechatStatusSystemModified($livechat_status_system_modified)
    {
        $this->container['livechat_status_system_modified'] = $livechat_status_system_modified;

        return $this;
    }

    /**
     * Gets status_livechat
     *
     * @return string
     */
    public function getStatusLivechat()
    {
        return $this->container['status_livechat'];
    }

    /**
     * Sets status_livechat
     *
     * @param string $status_livechat status_livechat
     *
     * @return $this
     */
    public function setStatusLivechat($status_livechat)
    {
        $this->container['status_livechat'] = $status_livechat;

        return $this;
    }

    /**
     * Gets livechat_count
     *
     * @return int
     */
    public function getLivechatCount()
    {
        return $this->container['livechat_count'];
    }

    /**
     * Sets livechat_count
     *
     * @param int $livechat_count livechat_count
     *
     * @return $this
     */
    public function setLivechatCount($livechat_count)
    {
        $this->container['livechat_count'] = $livechat_count;

        return $this;
    }

    /**
     * Gets livechat
     *
     * @return \Swagger\Client\Model\InlineResponse20011UserLivechat
     */
    public function getLivechat()
    {
        return $this->container['livechat'];
    }

    /**
     * Sets livechat
     *
     * @param \Swagger\Client\Model\InlineResponse20011UserLivechat $livechat livechat
     *
     * @return $this
     */
    public function setLivechat($livechat)
    {
        $this->container['livechat'] = $livechat;

        return $this;
    }

    /**
     * Gets bio
     *
     * @return string
     */
    public function getBio()
    {
        return $this->container['bio'];
    }

    /**
     * Sets bio
     *
     * @param string $bio bio
     *
     * @return $this
     */
    public function setBio($bio)
    {
        $this->container['bio'] = $bio;

        return $this;
    }

    /**
     * Gets nickname
     *
     * @return string
     */
    public function getNickname()
    {
        return $this->container['nickname'];
    }

    /**
     * Sets nickname
     *
     * @param string $nickname nickname
     *
     * @return $this
     */
    public function setNickname($nickname)
    {
        $this->container['nickname'] = $nickname;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
