<?php
/**
 * InlineResponse2009LicensePreventedActionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Miscellaneous
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2009LicensePreventedActionsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2009LicensePreventedActions
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2009LicensePreventedActionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2009LicensePreventedActions"
     */
    public function testInlineResponse2009LicensePreventedActions()
    {
    }

    /**
     * Test attribute "active_users"
     */
    public function testPropertyActiveUsers()
    {
    }

    /**
     * Test attribute "guest_users"
     */
    public function testPropertyGuestUsers()
    {
    }

    /**
     * Test attribute "rooms_per_guest"
     */
    public function testPropertyRoomsPerGuest()
    {
    }

    /**
     * Test attribute "private_apps"
     */
    public function testPropertyPrivateApps()
    {
    }

    /**
     * Test attribute "marketplace_apps"
     */
    public function testPropertyMarketplaceApps()
    {
    }

    /**
     * Test attribute "monthly_active_contacts"
     */
    public function testPropertyMonthlyActiveContacts()
    {
    }
}
