<?php
/**
 * V1AssetsSetAssetBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Content Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * V1AssetsSetAssetBodyTest Class Doc Comment
 *
 * @category    Class
 * @description V1AssetsSetAssetBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1AssetsSetAssetBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1AssetsSetAssetBody"
     */
    public function testV1AssetsSetAssetBody()
    {
    }

    /**
     * Test attribute "asset"
     */
    public function testPropertyAsset()
    {
    }

    /**
     * Test attribute "asset_name"
     */
    public function testPropertyAssetName()
    {
    }

    /**
     * Test attribute "refresh_all_clients"
     */
    public function testPropertyRefreshAllClients()
    {
    }
}
