<?php
/**
 * InlineResponse2004IntegrationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Integrations
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2004IntegrationTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2004Integration
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2004IntegrationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2004Integration"
     */
    public function testInlineResponse2004Integration()
    {
    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "avatar_url"
     */
    public function testPropertyAvatarUrl()
    {
    }

    /**
     * Test attribute "emoji"
     */
    public function testPropertyEmoji()
    {
    }

    /**
     * Test attribute "script_enabled"
     */
    public function testPropertyScriptEnabled()
    {
    }

    /**
     * Test attribute "script"
     */
    public function testPropertyScript()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "_created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "_created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "_updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "_updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
