<?php
/**
 * InlineResponse20026Ims
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Messaging
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * InlineResponse20026Ims Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20026Ims implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_26_ims';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        '_id' => 'string',
        't' => 'string',
        'usernames' => 'string[]',
        'users_count' => 'int',
        'msgs' => 'int',
        'ts' => 'string',
        'uids' => 'string[]',
        'encrypted' => 'bool',
        'default' => 'bool',
        'ro' => 'bool',
        'sys_mes' => 'bool',
        '_updated_at' => 'string',
        '_usernames' => 'string[]',
        'e2e_key_id' => 'string',
        'last_message' => '\Swagger\Client\Model\InlineResponse2007Messages',
        'lm' => 'string',
        'topic' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        '_id' => null,
        't' => null,
        'usernames' => null,
        'users_count' => null,
        'msgs' => null,
        'ts' => null,
        'uids' => null,
        'encrypted' => null,
        'default' => null,
        'ro' => null,
        'sys_mes' => null,
        '_updated_at' => null,
        '_usernames' => null,
        'e2e_key_id' => null,
        'last_message' => null,
        'lm' => null,
        'topic' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_id' => '_id',
        't' => 't',
        'usernames' => 'usernames',
        'users_count' => 'usersCount',
        'msgs' => 'msgs',
        'ts' => 'ts',
        'uids' => 'uids',
        'encrypted' => 'encrypted',
        'default' => 'default',
        'ro' => 'ro',
        'sys_mes' => 'sysMes',
        '_updated_at' => '_updatedAt',
        '_usernames' => '_USERNAMES',
        'e2e_key_id' => 'e2eKeyId',
        'last_message' => 'lastMessage',
        'lm' => 'lm',
        'topic' => 'topic'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_id' => 'setId',
        't' => 'setT',
        'usernames' => 'setUsernames',
        'users_count' => 'setUsersCount',
        'msgs' => 'setMsgs',
        'ts' => 'setTs',
        'uids' => 'setUids',
        'encrypted' => 'setEncrypted',
        'default' => 'setDefault',
        'ro' => 'setRo',
        'sys_mes' => 'setSysMes',
        '_updated_at' => 'setUpdatedAt',
        '_usernames' => 'setUsernames',
        'e2e_key_id' => 'setE2eKeyId',
        'last_message' => 'setLastMessage',
        'lm' => 'setLm',
        'topic' => 'setTopic'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_id' => 'getId',
        't' => 'getT',
        'usernames' => 'getUsernames',
        'users_count' => 'getUsersCount',
        'msgs' => 'getMsgs',
        'ts' => 'getTs',
        'uids' => 'getUids',
        'encrypted' => 'getEncrypted',
        'default' => 'getDefault',
        'ro' => 'getRo',
        'sys_mes' => 'getSysMes',
        '_updated_at' => 'getUpdatedAt',
        '_usernames' => 'getUsernames',
        'e2e_key_id' => 'getE2eKeyId',
        'last_message' => 'getLastMessage',
        'lm' => 'getLm',
        'topic' => 'getTopic'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_id'] = isset($data['_id']) ? $data['_id'] : null;
        $this->container['t'] = isset($data['t']) ? $data['t'] : null;
        $this->container['usernames'] = isset($data['usernames']) ? $data['usernames'] : null;
        $this->container['users_count'] = isset($data['users_count']) ? $data['users_count'] : null;
        $this->container['msgs'] = isset($data['msgs']) ? $data['msgs'] : null;
        $this->container['ts'] = isset($data['ts']) ? $data['ts'] : null;
        $this->container['uids'] = isset($data['uids']) ? $data['uids'] : null;
        $this->container['encrypted'] = isset($data['encrypted']) ? $data['encrypted'] : null;
        $this->container['default'] = isset($data['default']) ? $data['default'] : null;
        $this->container['ro'] = isset($data['ro']) ? $data['ro'] : null;
        $this->container['sys_mes'] = isset($data['sys_mes']) ? $data['sys_mes'] : null;
        $this->container['_updated_at'] = isset($data['_updated_at']) ? $data['_updated_at'] : null;
        $this->container['_usernames'] = isset($data['_usernames']) ? $data['_usernames'] : null;
        $this->container['e2e_key_id'] = isset($data['e2e_key_id']) ? $data['e2e_key_id'] : null;
        $this->container['last_message'] = isset($data['last_message']) ? $data['last_message'] : null;
        $this->container['lm'] = isset($data['lm']) ? $data['lm'] : null;
        $this->container['topic'] = isset($data['topic']) ? $data['topic'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['_id'];
    }

    /**
     * Sets _id
     *
     * @param string $_id _id
     *
     * @return $this
     */
    public function setId($_id)
    {
        $this->container['_id'] = $_id;

        return $this;
    }

    /**
     * Gets t
     *
     * @return string
     */
    public function getT()
    {
        return $this->container['t'];
    }

    /**
     * Sets t
     *
     * @param string $t t
     *
     * @return $this
     */
    public function setT($t)
    {
        $this->container['t'] = $t;

        return $this;
    }

    /**
     * Gets usernames
     *
     * @return string[]
     */
    public function getUsernames()
    {
        return $this->container['usernames'];
    }

    /**
     * Sets usernames
     *
     * @param string[] $usernames usernames
     *
     * @return $this
     */
    public function setUsernames($usernames)
    {
        $this->container['usernames'] = $usernames;

        return $this;
    }

    /**
     * Gets users_count
     *
     * @return int
     */
    public function getUsersCount()
    {
        return $this->container['users_count'];
    }

    /**
     * Sets users_count
     *
     * @param int $users_count users_count
     *
     * @return $this
     */
    public function setUsersCount($users_count)
    {
        $this->container['users_count'] = $users_count;

        return $this;
    }

    /**
     * Gets msgs
     *
     * @return int
     */
    public function getMsgs()
    {
        return $this->container['msgs'];
    }

    /**
     * Sets msgs
     *
     * @param int $msgs msgs
     *
     * @return $this
     */
    public function setMsgs($msgs)
    {
        $this->container['msgs'] = $msgs;

        return $this;
    }

    /**
     * Gets ts
     *
     * @return string
     */
    public function getTs()
    {
        return $this->container['ts'];
    }

    /**
     * Sets ts
     *
     * @param string $ts ts
     *
     * @return $this
     */
    public function setTs($ts)
    {
        $this->container['ts'] = $ts;

        return $this;
    }

    /**
     * Gets uids
     *
     * @return string[]
     */
    public function getUids()
    {
        return $this->container['uids'];
    }

    /**
     * Sets uids
     *
     * @param string[] $uids uids
     *
     * @return $this
     */
    public function setUids($uids)
    {
        $this->container['uids'] = $uids;

        return $this;
    }

    /**
     * Gets encrypted
     *
     * @return bool
     */
    public function getEncrypted()
    {
        return $this->container['encrypted'];
    }

    /**
     * Sets encrypted
     *
     * @param bool $encrypted encrypted
     *
     * @return $this
     */
    public function setEncrypted($encrypted)
    {
        $this->container['encrypted'] = $encrypted;

        return $this;
    }

    /**
     * Gets default
     *
     * @return bool
     */
    public function getDefault()
    {
        return $this->container['default'];
    }

    /**
     * Sets default
     *
     * @param bool $default default
     *
     * @return $this
     */
    public function setDefault($default)
    {
        $this->container['default'] = $default;

        return $this;
    }

    /**
     * Gets ro
     *
     * @return bool
     */
    public function getRo()
    {
        return $this->container['ro'];
    }

    /**
     * Sets ro
     *
     * @param bool $ro ro
     *
     * @return $this
     */
    public function setRo($ro)
    {
        $this->container['ro'] = $ro;

        return $this;
    }

    /**
     * Gets sys_mes
     *
     * @return bool
     */
    public function getSysMes()
    {
        return $this->container['sys_mes'];
    }

    /**
     * Sets sys_mes
     *
     * @param bool $sys_mes sys_mes
     *
     * @return $this
     */
    public function setSysMes($sys_mes)
    {
        $this->container['sys_mes'] = $sys_mes;

        return $this;
    }

    /**
     * Gets _updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['_updated_at'];
    }

    /**
     * Sets _updated_at
     *
     * @param string $_updated_at _updated_at
     *
     * @return $this
     */
    public function setUpdatedAt($_updated_at)
    {
        $this->container['_updated_at'] = $_updated_at;

        return $this;
    }

    /**
     * Gets _usernames
     *
     * @return string[]
     */
    public function getUsernames()
    {
        return $this->container['_usernames'];
    }

    /**
     * Sets _usernames
     *
     * @param string[] $_usernames _usernames
     *
     * @return $this
     */
    public function setUsernames($_usernames)
    {
        $this->container['_usernames'] = $_usernames;

        return $this;
    }

    /**
     * Gets e2e_key_id
     *
     * @return string
     */
    public function getE2eKeyId()
    {
        return $this->container['e2e_key_id'];
    }

    /**
     * Sets e2e_key_id
     *
     * @param string $e2e_key_id e2e_key_id
     *
     * @return $this
     */
    public function setE2eKeyId($e2e_key_id)
    {
        $this->container['e2e_key_id'] = $e2e_key_id;

        return $this;
    }

    /**
     * Gets last_message
     *
     * @return \Swagger\Client\Model\InlineResponse2007Messages
     */
    public function getLastMessage()
    {
        return $this->container['last_message'];
    }

    /**
     * Sets last_message
     *
     * @param \Swagger\Client\Model\InlineResponse2007Messages $last_message last_message
     *
     * @return $this
     */
    public function setLastMessage($last_message)
    {
        $this->container['last_message'] = $last_message;

        return $this;
    }

    /**
     * Gets lm
     *
     * @return string
     */
    public function getLm()
    {
        return $this->container['lm'];
    }

    /**
     * Sets lm
     *
     * @param string $lm lm
     *
     * @return $this
     */
    public function setLm($lm)
    {
        $this->container['lm'] = $lm;

        return $this;
    }

    /**
     * Gets topic
     *
     * @return string
     */
    public function getTopic()
    {
        return $this->container['topic'];
    }

    /**
     * Sets topic
     *
     * @param string $topic topic
     *
     * @return $this
     */
    public function setTopic($topic)
    {
        $this->container['topic'] = $topic;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
