<?php
/**
 * InlineResponse2001EnterpriseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Statistics
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2001EnterpriseTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2001Enterprise
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2001EnterpriseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2001Enterprise"
     */
    public function testInlineResponse2001Enterprise()
    {
    }

    /**
     * Test attribute "modules"
     */
    public function testPropertyModules()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "seat_requests"
     */
    public function testPropertySeatRequests()
    {
    }

    /**
     * Test attribute "canned_responses"
     */
    public function testPropertyCannedResponses()
    {
    }

    /**
     * Test attribute "livechat_tags"
     */
    public function testPropertyLivechatTags()
    {
    }

    /**
     * Test attribute "slas"
     */
    public function testPropertySlas()
    {
    }

    /**
     * Test attribute "omnichannel_rooms_with_priorities"
     */
    public function testPropertyOmnichannelRoomsWithPriorities()
    {
    }

    /**
     * Test attribute "omnichannel_rooms_with_slas"
     */
    public function testPropertyOmnichannelRoomsWithSlas()
    {
    }

    /**
     * Test attribute "business_units"
     */
    public function testPropertyBusinessUnits()
    {
    }

    /**
     * Test attribute "livechat_monitors"
     */
    public function testPropertyLivechatMonitors()
    {
    }

    /**
     * Test attribute "omnichannel_pdf_transcript_succeeded"
     */
    public function testPropertyOmnichannelPdfTranscriptSucceeded()
    {
    }

    /**
     * Test attribute "omnichannel_pdf_transcript_requested"
     */
    public function testPropertyOmnichannelPdfTranscriptRequested()
    {
    }
}
