<?php
/**
 * InlineResponse2008LastMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rooms
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.67
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2008LastMessageTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2008LastMessage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2008LastMessageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2008LastMessage"
     */
    public function testInlineResponse2008LastMessage()
    {
    }

    /**
     * Test attribute "_id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "t"
     */
    public function testPropertyT()
    {
    }

    /**
     * Test attribute "msg"
     */
    public function testPropertyMsg()
    {
    }

    /**
     * Test attribute "groupable"
     */
    public function testPropertyGroupable()
    {
    }

    /**
     * Test attribute "blocks"
     */
    public function testPropertyBlocks()
    {
    }

    /**
     * Test attribute "ts"
     */
    public function testPropertyTs()
    {
    }

    /**
     * Test attribute "u"
     */
    public function testPropertyU()
    {
    }

    /**
     * Test attribute "rid"
     */
    public function testPropertyRid()
    {
    }

    /**
     * Test attribute "_updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "urls"
     */
    public function testPropertyUrls()
    {
    }

    /**
     * Test attribute "mentions"
     */
    public function testPropertyMentions()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }

    /**
     * Test attribute "md"
     */
    public function testPropertyMd()
    {
    }
}
